openapi: 3.0.0
info:
  title: API CPF Web
  description: Todos os métodos disponíveis na nossa API REST
  version: 1.0.0

servers:
  - url: http://localhost:5000/api

tags:
  - name: Países
    description: Operações com países
  - name: Estados
    description: Operações com estados
  - name: Cidades
    description: Operações com cidades
  - name: Bairros
    description: Operações com bairros
  - name: Endereços
    description: Operações com endereços
  - name: Pessoas
    description: Operações com pessoas

paths:
  /paises:
    get:
      tags:
        - Países
      description: Retornar todos os países.
      responses:
        200:
          description: Conseguiu retornar com sucesso
    post:
      tags:
        - Países
      description: Cadastra um novo pais
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: ''
      responses:
        200:
          description: Cadastro realizado com sucesso
  
  /paises/{pais_id}:
    delete:
      tags:
        - Países
      operationId: "deletePais"
      parameters:
        - name: pais_id
          in: path
          description: ID de um país
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: O pais foi excluído com sucesso
    put:
      tags:
        - Países
      parameters:
        - name: pais_id
          in: path
          description: ID de um país
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: ''
      responses:
        200:
          description: O pais foi editado com sucesso
    
  /paises/{pais_id}/estados:
    get:
      tags:
        - Estados
      description: Retornar todos os estados de um país.
      operationId: get_estados
      parameters:
        - name: pais_id
          in: path
          description: ID de um país
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Conseguiu retornar com sucesso
    
  /estados:
    post:
      tags:
        - Estados
      responses:
        200:
          description: Conseguiu retornar com sucesso
    
  /paises/{pais_id}/cidades:
    get:
      tags:
        - Cidades
      description: Retornar todos as cidades de um país.
      operationId: get_cidades
      parameters:
        - name: pais_id
          in: path
          description: ID de um país
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Conseguiu retornar com sucesso
  
  /paises/{pais_id}/bairros:
    get:
      tags:
        - Bairros
      description: Retornar todos os bairros de um país.
      operationId: get_bairro
      parameters:
        - name: pais_id
          in: path
          description: ID de um país
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Conseguiu retornar com sucesso
          
  /enderecos:
    get:
      tags:
        - Endereços
      description: Retornar todos os endereços.
      operationId: get_endereco
      responses:
        200:
          description: Conseguiu retornar com sucesso
    post:
      tags:
          - Endereços
      description: Cadastra um endereços.
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: ''
      responses:
        200:
          description: Cadastrado com sucesso
          
  /enderecos/{endereco_id}:
    put:
      tags:
        - Endereços
      parameters:
        - name: endereco_id
          in: path
          description: id de um endereço
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: ''
      responses:
        200:
          description: O pais foi editado com sucesso
    delete:
      tags:
        - Endereços
      parameters:
        - name: endereco_id
          in: path
          description: id de um endereço
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: O endereço foi editado com sucesso
   
  
  /pessoas/{cpf}:
    get:
      tags:
        - Pessoas
      description: Retornar uma pessoa
      operationId: get_Pessoa
      parameters:
        - name: cpf
          in: path
          description: CPF de uma pessoa
          required: true
          schema:
            type: "string"

      responses:
        200:
          description: Conseguiu retornar com sucesso 
          
  /pessoas:
    get:
      tags:
        - Pessoas
      description: Retornar todos as pessoas.
      operationId: get_Pessoas
      responses:
        200:
          description: Conseguiu retornar com sucesso
    post:
      tags:
        - Pessoas
      responses:
        200:
          description: Conseguiu retornar com sucesso
          
  /pessoas/{pessoa_id}:
    put:
      tags:
        - Pessoas
      parameters:
        - name: pessoa_id
          in: path
          description: ID de uma pessoa
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: ''
      responses:
        200:
          description: O pais foi editado com sucess
    delete:
      tags:
        - Pessoas
      description: Retornar todos as pessoas.
      operationId: delete_Pessoa
      parameters:
        - name: pessoa_id
          in: path
          description: ID de uma pessoa
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Conseguiu retornar com sucesso